### ISSUE TITLE
Clean Error Log

### ISSUE THREAD

**Issue by MightNight** [ck2plus/CK2Plus_OLD#134]
Hunt all the errors that are flooding the error log. They may be False Positives, but they can all be fixed with workarounds

**Comment by vukivan** [comment]
There are no false positives in the error log. Either error is in our script, or error is in the game itself.
But, it's important to have an empty log after game starts. Anything beyond that is probably paradox' fault.

**Comment by MightNight** [comment]
Oh boy. Gonna be fun sorting all those Duplicate Dynasties.
