### ISSUE TITLE
Create gfx assets for mysteries of mithras cult

### ISSUE THREAD

**Issue by vukivan** [ck2plus/CK2Plus_OLD#74]
Needs a new rank gfx + background.

Cult has 7 ranks, all of which have a certain symbol associated with it. (on wiki page)
Background should have the "bull" symbol as logo.

**Comment by schwarherz** [comment]
@vukivan Is this still needed?

**Comment by vukivan** [comment]
Depends on if you're planning to have the cult. We have raw material, I can easilly make icons.
